name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow workflow to push commits

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Auto-bump version
        id: ver
        run: |
          if [ -f VERSION ]; then
            current=$(cat VERSION | tr -d '[:space:]')
            version=${current#v}
            IFS='.' read -r major minor patch <<< "$version"
            new_patch=$((patch + 1))
            new_version="v${major}.${minor}.${new_patch}"
            echo "$new_version" > VERSION
            echo "version=$new_version" >> $GITHUB_OUTPUT
            git add VERSION
            git commit -m "bump version to $new_version [skip ci]"
            git push
          else
            echo "version=dev" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docker-optimized:${{ steps.ver.outputs.version }}
